/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EncodeSubstandard5ForEthersInterface extends Interface {
  getFunction(nameOrSignature: "encodeSubstandard5"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "encodeSubstandard5",
    values: [
      BigNumberish[],
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike[],
      BytesLike[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "encodeSubstandard5",
    data: BytesLike
  ): Result;
}

export interface EncodeSubstandard5ForEthers extends BaseContract {
  connect(runner?: ContractRunner | null): EncodeSubstandard5ForEthers;
  waitForDeployment(): Promise<this>;

  interface: EncodeSubstandard5ForEthersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encodeSubstandard5: TypedContractMethod<
    [
      comparisonEnums: BigNumberish[],
      token: AddressLike,
      traits: AddressLike,
      identifier: BigNumberish,
      traitValues: BytesLike[],
      traitKeys: BytesLike[]
    ],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encodeSubstandard5"
  ): TypedContractMethod<
    [
      comparisonEnums: BigNumberish[],
      token: AddressLike,
      traits: AddressLike,
      identifier: BigNumberish,
      traitValues: BytesLike[],
      traitKeys: BytesLike[]
    ],
    [string],
    "view"
  >;

  filters: {};
}
