/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SepoliaContractsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AccountingEngine_Address"
      | "AccountingJob_Address"
      | "BasicActions_Address"
      | "ChainlinkRelayerChild_8_Address"
      | "ChainlinkRelayerFactory_Address"
      | "CoinJoin_Address"
      | "CollateralAuctionHouseChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address"
      | "CollateralAuctionHouseChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address"
      | "CollateralAuctionHouseChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address"
      | "CollateralAuctionHouseChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address"
      | "CollateralAuctionHouseFactory_Address"
      | "CollateralBidActions_Address"
      | "CollateralJoinChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address"
      | "CollateralJoinChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address"
      | "CollateralJoinChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address"
      | "CollateralJoinChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address"
      | "CollateralJoinFactory_Address"
      | "DebtAuctionHouse_Address"
      | "DebtBidActions_Address"
      | "DelayedOracleChild_ARB_Address"
      | "DelayedOracleChild_CBETH_Address"
      | "DelayedOracleChild_RETH_Address"
      | "DelayedOracleChild_WSTETH_Address"
      | "DelayedOracleFactory_Address"
      | "DenominatedOracleChild_ARB_Address"
      | "DenominatedOracleChild_RETH_Address"
      | "DenominatedOracleFactory_Address"
      | "GlobalSettlementActions_Address"
      | "GlobalSettlement_Address"
      | "LiquidationEngine_Address"
      | "LiquidationJob_Address"
      | "MintableERC20_CBETH_Address"
      | "MintableERC20_RETH_Address"
      | "MintableERC20_WSTETH_Address"
      | "MintableVoteERC20_ARB_Address"
      | "NFTRenderer_Address"
      | "ODGovernor_Address"
      | "ODSafeManager_Address"
      | "OracleJob_Address"
      | "OracleRelayer_Address"
      | "PIDController_Address"
      | "PIDRateSetter_Address"
      | "PostSettlementSurplusAuctionHouse_Address"
      | "PostSettlementSurplusBidActions_Address"
      | "ProtocolToken_Address"
      | "RewardedActions_Address"
      | "SAFEEngine_Address"
      | "SettlementSurplusAuctioneer_Address"
      | "StabilityFeeTreasury_Address"
      | "SurplusAuctionHouse_Address"
      | "SurplusBidActions_Address"
      | "SystemCoin_Address"
      | "TaxCollector_Address"
      | "TimelockController_Address"
      | "Vault721_Address"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "AccountingEngine_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AccountingJob_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BasicActions_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ChainlinkRelayerChild_8_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ChainlinkRelayerFactory_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CoinJoin_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralAuctionHouseChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralAuctionHouseChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralAuctionHouseChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralAuctionHouseChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralAuctionHouseFactory_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralBidActions_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralJoinChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralJoinChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralJoinChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralJoinChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CollateralJoinFactory_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DebtAuctionHouse_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DebtBidActions_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DelayedOracleChild_ARB_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DelayedOracleChild_CBETH_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DelayedOracleChild_RETH_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DelayedOracleChild_WSTETH_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DelayedOracleFactory_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DenominatedOracleChild_ARB_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DenominatedOracleChild_RETH_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DenominatedOracleFactory_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GlobalSettlementActions_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GlobalSettlement_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LiquidationEngine_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LiquidationJob_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MintableERC20_CBETH_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MintableERC20_RETH_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MintableERC20_WSTETH_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MintableVoteERC20_ARB_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NFTRenderer_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ODGovernor_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ODSafeManager_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OracleJob_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OracleRelayer_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PIDController_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PIDRateSetter_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PostSettlementSurplusAuctionHouse_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PostSettlementSurplusBidActions_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ProtocolToken_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RewardedActions_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAFEEngine_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SettlementSurplusAuctioneer_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "StabilityFeeTreasury_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SurplusAuctionHouse_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SurplusBidActions_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SystemCoin_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TaxCollector_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TimelockController_Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "Vault721_Address",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AccountingEngine_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AccountingJob_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BasicActions_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ChainlinkRelayerChild_8_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ChainlinkRelayerFactory_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CoinJoin_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralAuctionHouseChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralAuctionHouseChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralAuctionHouseChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralAuctionHouseChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralAuctionHouseFactory_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralBidActions_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralJoinChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralJoinChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralJoinChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralJoinChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CollateralJoinFactory_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DebtAuctionHouse_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DebtBidActions_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DelayedOracleChild_ARB_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DelayedOracleChild_CBETH_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DelayedOracleChild_RETH_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DelayedOracleChild_WSTETH_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DelayedOracleFactory_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DenominatedOracleChild_ARB_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DenominatedOracleChild_RETH_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DenominatedOracleFactory_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GlobalSettlementActions_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GlobalSettlement_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LiquidationEngine_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LiquidationJob_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MintableERC20_CBETH_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MintableERC20_RETH_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MintableERC20_WSTETH_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MintableVoteERC20_ARB_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NFTRenderer_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ODGovernor_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ODSafeManager_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OracleJob_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OracleRelayer_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PIDController_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PIDRateSetter_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PostSettlementSurplusAuctionHouse_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PostSettlementSurplusBidActions_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ProtocolToken_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RewardedActions_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAFEEngine_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SettlementSurplusAuctioneer_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "StabilityFeeTreasury_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SurplusAuctionHouse_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SurplusBidActions_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SystemCoin_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TaxCollector_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TimelockController_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "Vault721_Address",
    data: BytesLike
  ): Result;
}

export interface SepoliaContracts extends BaseContract {
  connect(runner?: ContractRunner | null): SepoliaContracts;
  waitForDeployment(): Promise<this>;

  interface: SepoliaContractsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AccountingEngine_Address: TypedContractMethod<[], [string], "view">;

  AccountingJob_Address: TypedContractMethod<[], [string], "view">;

  BasicActions_Address: TypedContractMethod<[], [string], "view">;

  ChainlinkRelayerChild_8_Address: TypedContractMethod<[], [string], "view">;

  ChainlinkRelayerFactory_Address: TypedContractMethod<[], [string], "view">;

  CoinJoin_Address: TypedContractMethod<[], [string], "view">;

  CollateralAuctionHouseChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralAuctionHouseChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralAuctionHouseChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralAuctionHouseChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralAuctionHouseFactory_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralBidActions_Address: TypedContractMethod<[], [string], "view">;

  CollateralJoinChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralJoinChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralJoinChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralJoinChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  CollateralJoinFactory_Address: TypedContractMethod<[], [string], "view">;

  DebtAuctionHouse_Address: TypedContractMethod<[], [string], "view">;

  DebtBidActions_Address: TypedContractMethod<[], [string], "view">;

  DelayedOracleChild_ARB_Address: TypedContractMethod<[], [string], "view">;

  DelayedOracleChild_CBETH_Address: TypedContractMethod<[], [string], "view">;

  DelayedOracleChild_RETH_Address: TypedContractMethod<[], [string], "view">;

  DelayedOracleChild_WSTETH_Address: TypedContractMethod<[], [string], "view">;

  DelayedOracleFactory_Address: TypedContractMethod<[], [string], "view">;

  DenominatedOracleChild_ARB_Address: TypedContractMethod<[], [string], "view">;

  DenominatedOracleChild_RETH_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  DenominatedOracleFactory_Address: TypedContractMethod<[], [string], "view">;

  GlobalSettlementActions_Address: TypedContractMethod<[], [string], "view">;

  GlobalSettlement_Address: TypedContractMethod<[], [string], "view">;

  LiquidationEngine_Address: TypedContractMethod<[], [string], "view">;

  LiquidationJob_Address: TypedContractMethod<[], [string], "view">;

  MintableERC20_CBETH_Address: TypedContractMethod<[], [string], "view">;

  MintableERC20_RETH_Address: TypedContractMethod<[], [string], "view">;

  MintableERC20_WSTETH_Address: TypedContractMethod<[], [string], "view">;

  MintableVoteERC20_ARB_Address: TypedContractMethod<[], [string], "view">;

  NFTRenderer_Address: TypedContractMethod<[], [string], "view">;

  ODGovernor_Address: TypedContractMethod<[], [string], "view">;

  ODSafeManager_Address: TypedContractMethod<[], [string], "view">;

  OracleJob_Address: TypedContractMethod<[], [string], "view">;

  OracleRelayer_Address: TypedContractMethod<[], [string], "view">;

  PIDController_Address: TypedContractMethod<[], [string], "view">;

  PIDRateSetter_Address: TypedContractMethod<[], [string], "view">;

  PostSettlementSurplusAuctionHouse_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  PostSettlementSurplusBidActions_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  ProtocolToken_Address: TypedContractMethod<[], [string], "view">;

  RewardedActions_Address: TypedContractMethod<[], [string], "view">;

  SAFEEngine_Address: TypedContractMethod<[], [string], "view">;

  SettlementSurplusAuctioneer_Address: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  StabilityFeeTreasury_Address: TypedContractMethod<[], [string], "view">;

  SurplusAuctionHouse_Address: TypedContractMethod<[], [string], "view">;

  SurplusBidActions_Address: TypedContractMethod<[], [string], "view">;

  SystemCoin_Address: TypedContractMethod<[], [string], "view">;

  TaxCollector_Address: TypedContractMethod<[], [string], "view">;

  TimelockController_Address: TypedContractMethod<[], [string], "view">;

  Vault721_Address: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AccountingEngine_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AccountingJob_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BasicActions_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ChainlinkRelayerChild_8_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ChainlinkRelayerFactory_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CoinJoin_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralAuctionHouseChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralAuctionHouseChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralAuctionHouseChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralAuctionHouseChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralAuctionHouseFactory_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralBidActions_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralJoinChild_0x4152420000000000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralJoinChild_0x4342455448000000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralJoinChild_0x5245544800000000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralJoinChild_0x5753544554480000000000000000000000000000000000000000000000000000_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CollateralJoinFactory_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DebtAuctionHouse_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DebtBidActions_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DelayedOracleChild_ARB_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DelayedOracleChild_CBETH_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DelayedOracleChild_RETH_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DelayedOracleChild_WSTETH_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DelayedOracleFactory_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DenominatedOracleChild_ARB_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DenominatedOracleChild_RETH_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DenominatedOracleFactory_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GlobalSettlementActions_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GlobalSettlement_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LiquidationEngine_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LiquidationJob_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MintableERC20_CBETH_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MintableERC20_RETH_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MintableERC20_WSTETH_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MintableVoteERC20_ARB_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NFTRenderer_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ODGovernor_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ODSafeManager_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OracleJob_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OracleRelayer_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIDController_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PIDRateSetter_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PostSettlementSurplusAuctionHouse_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PostSettlementSurplusBidActions_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ProtocolToken_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RewardedActions_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SAFEEngine_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SettlementSurplusAuctioneer_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "StabilityFeeTreasury_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SurplusAuctionHouse_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SurplusBidActions_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SystemCoin_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TaxCollector_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TimelockController_Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "Vault721_Address"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
